import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ModalProvider } from "@/providers/ModalProvider";
import { poppins } from "./fonts";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { QClientProvider } from "@/providers/QueryClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={poppins.className}>
          <QClientProvider>
            {children}
            <ModalProvider />
            <Toaster richColors />
          </QClientProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
